import Head from 'next/head';
import Image from 'next/image';

import vercelImg from '/public/vercel.svg';

const data = [
  { id: 1, title: 'Movie Title 1', genres: ['action'], year: '2020' },
  { id: 2, title: 'Movie Title 2', genres: ['adventure', 'action'], year: '2021' },
  { id: 3, title: 'Movie Title 3', genres: ['adventure', 'crime'], year: '2019' },
  { id: 4, title: 'Movie Title 4', genres: ['adventure', 'fantasy'], year: '2019' },
  { id: 5, title: 'Movie Title 5', genres: ['adventure', 'sci-fi'], year: '2017' },
  { id: 6, title: 'Movie Title 6', genres: ['documentary', 'biography'], year: '2018' },
  { id: 7, title: 'Movie Title 7', genres: ['documentary', 'biography'], year: '2014' },
  { id: 8, title: 'Movie Title 8', genres: ['documentary', 'biography'], year: '2014' },
  { id: 9, title: 'Movie Title 9', genres: ['documentary', 'biography'], year: '2013' },
  { id: 10, title: 'Movie Title 10', genres: ['documentary', 'biography'], year: '2012' },
];

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full bg-gray-800 min-h-screen'>
        <nav className='w-full bg-gray-900 py-2'>
          <h1 className='mx-auto text-center text-emerald-500 xl:text-4xl lg:text-3xl'>MovieRama</h1>
        </nav>
        <section className='w-full bg-gray-900 py-5 sm:py-10 mx-auto text-center flex justify-center items-end border-b border-b-emerald-900'>
          <div className='max-w-7xl w-full px-4'>
            <input
              type='text'
              placeholder='Search for a title'
              className='px-4 py-2 text-lg w-full xl:w-1/2 lg:w-2/3 md:w-2/3 sm:w-4/5 focus:outline-none bg-gray-700 text-emerald-300 border border-emerald-300 rounded'
            />
          </div>
        </section>
        <section className=''>
          <div
            className={`
              max-w-7xl bg-gray-700 min-h-screen mx-auto p-5 pt-10 grid grid-cols-1 gap-5
              xl:grid-cols-5 lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 
            `}>
            {data.map((movie) => {
              return (
                <div
                  key={movie.id}
                  className='min-h-min border-2 rounded border-yellow-400 bg-emerald-700 flex flex-col justify-between'
                >
                  <Image src={vercelImg} alt='image' className='flex-grow' />
                  <div className='flex flex-wrap p-1 justify-start gap-1'>
                    {movie.genres.map(g => (
                      <span
                        key={g}
                        className='text-gray-800 font-medium p-1 border rounded border-white'
                      >
                          {g}
                      </span>
                    ))}
                  </div>
                  <div className='bg-yellow-300 text-amber-900 font-medium text-center py-2'>{movie.title} ({movie.year})</div>
                </div>
              );
            })}
          </div>
        </section>
      </main>
    </>
  );
}

export default Home;